[Variables]
ActiveColor=ffffff
InactiveColor=999999


w1=Dark Souls
w1_ext=.jpg
w1_run=steam://rungameid/211420
w1_color=#ActiveColor#

w2=Dark Souls II
w2_ext=.jpg
w2_run=steam://rungameid/335300
w2_color=#ActiveColor#

w3=Dark Souls III
w3_ext=.jpg
w3_run=steam://rungameid/374320
w3_color=#ActiveColor#

w4=Cave Story+
w4_ext=.png
w4_run=steam://rungameid/200900
w4_color=#ActiveColor#

w5=Undertale
w5_ext=.jpg
w5_run=steam://rungameid/391540
w5_color=#ActiveColor#

w6=Final Fantasy III
w6_ext=.jpg
w6_run=steam://rungameid/239120
w6_color=#ActiveColor#

w7=Mass Effect 3
w7_ext=.jpg
w7_run=O:\False Apparition\Program Files (x86)\Origin\Games\Mass Effect 3\Binaries\Win32\MassEffect3.exe
w7_color=#ActiveColor#

w8=ME Andromeda
w8_ext=.jpg
w8_run="O:\False Apparition\Program Files (x86)\Origin\Games\Mass Effect Andromeda\MassEffectAndromeda.exe"
w8_color=#ActiveColor#

w9=Borderlands
w9_ext=.jpg
w9_run=
w9_color=#ActiveColor#

w10=Borderlands 2
w10_ext=.jpg
w10_run=O:\Hidden Chest\Gaming\Cheats and Resources\Borderlands 2\bdl2.bat
w10_color=#ActiveColor#

w11=Borderlands TPS
w11_ext=.jpg
w11_run=steam://rungameid/261640
w11_color=#ActiveColor#

w12=CotND
w12_ext=.png
w12_run=steam://rungameid/247080
w12_color=#ActiveColor#

w13=Starbound
w13_ext=.jpg
w13_run=steam://rungameid/211820
w13_color=#ActiveColor#

w14=Spelunky
w14_ext=.jpg
w14_run=steam://rungameid/239350
w14_color=#ActiveColor#

w15=DOOM
w15_ext=.png
w15_run=steam://rungameid/379720
w15_color=#ActiveColor#